### ISSUE TITLE
Scala 3 migration checklist

### ISSUE THREAD

**Issue by kubukoz** [polyvariant/pitgull#171]
- Needs removing `*[_]` usage of kind-projector, as dotty doesn't support it (`*` works though)
- better-monadic-for needs investigating, possibly we can live without it

Releases for dependencies (that I see):

- [x] cats-effect
- [ ] cats-tagless - we might need to drop it or we'll have a long wait for the rewrite (macros)
- [x] fs2
- [x] http4s
- [x] odin
- [x] monocle (needs moving to 3.0.0 milestones, but they're source compatible so that's okay)
- [x] ciris (?)
- [ ] circe - generic-extras isn't migrated. We can probably hand-write the few codecs we have instead.
- [ ] tapir - we don't use it as much, might be able to remove it at some point when everything uses GraphQL
- [x] sttp
- [x] caliban-client
- [x] caliban-gitlab

**Comment by kubukoz** [comment]
ackshually we migrated in #431
