### ISSUE TITLE
Cats Effect 3 migration checklist

### ISSUE THREAD

**Issue by kubukoz** [polyvariant/pitgull#179]
Pending:

- [x] odin: WIP https://github.com/valskalla/odin/pull/273, pending release (snapshot: `0.11.0+3-19c38e47+20210402-1813-SNAPSHOT`)
- [x] sttp:
- [ ] ~~tapir: WIP https://github.com/softwaremill/tapir/pull/1154~~
- [x] prox: WIP https://github.com/vigoo/prox/pull/217, released
- [x] http4s

**Comment by kubukoz** [comment]
Current state:

- odin has a WIP PR
- sttp is waiting for tapir
- tapir is waiting for http4s
- prox is waiting for zio-interop-cats
- http4s is _published_ but it has a transitive dependency on CE3 RC2, which is actually binary compatible with CE3 final but will break sbt's eviction mechanism.

**Comment by kubukoz** [comment]
alright, looks like tapir will take ages to get there (blocked by catbird).

I have an idea: our main usage of it is in the clients, and we don't really need the server (come on, we have _one_ endpoint).

I think we can implement the endpoint directly in http4s, remove the tapir-http4s module and upgrade everything (sttp has CE2-compatible modules too) - then we can probably switch to CE3 "just like that".

**Comment by kubukoz** [comment]
There we go:

```diff
diff --git a/build.sbt b/build.sbt
index e3a4c40..5235af6 100644
--- a/build.sbt
+++ b/build.sbt
@@ -71,14 +71,14 @@ val commonSettings = List(
   scalacOptions += "-Ymacro-annotations",
   libraryDependencies ++= List(
     "org.typelevel" %% "cats-core" % "2.6.1",
-    "org.typelevel" %% "cats-effect" % "2.5.1",
+    "org.typelevel" %% "cats-effect" % "3.1.1",
     "org.typelevel" %% "cats-tagless-macros" % "0.14.0",
-    "co.fs2" %% "fs2-core" % "2.5.6",
-    "com.github.valskalla" %% "odin-core" % "0.11.0",
+    "co.fs2" %% "fs2-core" % "3.0.4",
+    "com.github.valskalla" %% "odin-core" % "0.11.0+7-4b29a367-SNAPSHOT",
     "io.circe" %% "circe-core" % "0.13.0",
     "com.github.julien-truffaut" %% "monocle-macro" % "2.1.0",
-    "com.disneystreaming" %% "weaver-framework" % "0.5.1" % Test,
-    "com.disneystreaming" %% "weaver-scalacheck" % "0.5.1" % Test
+    "com.disneystreaming" %% "weaver-framework" % "0.7.3" % Test,
+    "com.disneystreaming" %% "weaver-scalacheck" % "0.7.3" % Test
   ) ++ compilerPlugins,
   testFrameworks += new TestFramework("weaver.framework.TestFramework"),
   publish / skip := true
@@ -88,7 +88,7 @@ lazy val gitlab = project
   .settings(
     commonSettings,
     libraryDependencies ++= List(
-      "is.cir" %% "ciris" % "1.2.1",
+      "is.cir" %% "ciris" % "2.0.1",
       "com.kubukoz" %% "caliban-gitlab" % "0.0.14",
       "io.circe" %% "circe-generic-extras" % "0.13.0",
       "io.circe" %% "circe-parser" % "0.13.0" % Test,
@@ -143,19 +143,19 @@ lazy val pitgull =
       buildInfoPackage := "io.pg",
       buildInfoKeys := List(version, scalaVersion),
       libraryDependencies ++= List(
-        "com.softwaremill.sttp.client3" %% "http4s-backend" % "3.2.3",
-        "org.http4s" %% "http4s-dsl" % "0.21.24",
-        "org.http4s" %% "http4s-circe" % "0.21.24",
-        "org.http4s" %% "http4s-blaze-server" % "0.21.24",
-        "org.http4s" %% "http4s-blaze-client" % "0.21.24",
-        "is.cir" %% "ciris" % "1.2.1",
+        "com.softwaremill.sttp.client3" %% "http4s-backend" % "3.3.5",
+        "org.http4s" %% "http4s-dsl" % "0.23.0-M1",
+        "org.http4s" %% "http4s-circe" % "0.23.0-M1",
+        "org.http4s" %% "http4s-blaze-server" % "0.23.0-M1",
+        "org.http4s" %% "http4s-blaze-client" % "0.23.0-M1",
+        "is.cir" %% "ciris" % "2.0.1",
         "io.circe" %% "circe-generic-extras" % "0.13.0",
         "io.estatico" %% "newtype" % "0.4.4",
         "io.scalaland" %% "chimney" % "0.6.1",
         "io.chrisdavenport" %% "cats-time" % "0.3.4",
-        "com.github.valskalla" %% "odin-core" % "0.11.0",
-        "com.github.valskalla" %% "odin-slf4j" % "0.11.0",
-        "io.github.vigoo" %% "prox" % "0.5.2"
+        "com.github.valskalla" %% "odin-core" % "0.11.0+7-4b29a367-SNAPSHOT",
+        "com.github.valskalla" %% "odin-slf4j" % "0.11.0+7-4b29a367-SNAPSHOT",
+        "io.github.vigoo" %% "prox-fs2-3" % "0.7.0"
       )
     )
     .dependsOn(core, gitlab)
```

I'm just leaving this here for myself, might use this project for a video about upgrading CE3 :)

**Comment by majk-p** [comment]
It should be closed already with https://github.com/polyvariant/pitgull/pull/262

**Comment by kubukoz** [comment]
👍
